version: '3'
services:
  api:
    container_name: estimation-api
    restart: always
    build: ./api
    expose:
      - "5000"
    command: gunicorn -w 1 -b :5000 app:app
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api